---
# Creates vmadmin keypair that will be used to log into the Multipass VMs
# and the cloud-init file use when create the VMs.
- name: Create vmadmin key-pair
  ansible.builtin.shell: ssh-keygen -C vmadmin -N "" -f {{ tempfiles_root }}/multipass-certs/user_key
  delegate_to: localhost
- name: Create cloud-init file inserting the public key
  ansible.builtin.template:
    src: templates/cloud-init-template.j2
    dest: "{{ tempfiles_root }}/temp/cloud-init.yaml"
  delegate_to: localhost
  vars:
    public_key: "{{lookup('file', '{{ tempfiles_root }}/multipass-certs/user_key.pub')}}"